### ISSUE TITLE
[Sorun] "AttributeError: 'platform' modülü 'dist' özniteliğine sahip değil." hatası

### ISSUE THREAD

**Issue by Afacanc38** [efe3535/system-info-colorful#1]
## Uyguladığım adımlar

- Dosyanın bulunduğu dizine girdim
- Sağ tıklayıp "Uçbirimi burada aç" tuşuna bastım.
- `python3 system-info-colorful.py` komutunu girdim.
- Başlıktaki hatayı gördüm.

## Ekran görüntüleri
![Ekran Görüntüsü - 2021-05-21 13-43-00](https://user-images.githubusercontent.com/66299502/119125506-852b2980-ba3a-11eb-8ee1-560f177536c4.png)

## Ek notlar
python-color kütüphanesini kullanmanız için bana atıfta bulunmanız gerekmiyor.

**Comment by Afacanc38** [comment]
Haydaaa, bu sorun bildirimi de mi başıboş kaldı?

**Comment by efe3535** [comment]
Merhaba, çalışması gerekiyordu. platform.linux_distribution() dener misin? Buraları pek takip etmiyorum genelde, kusura bakma. :disappointed:

**Comment by efe3535** [comment]
Test edildi, çalışıyor. Sanırım deprecate edilmiş.

**Comment by efe3535** [comment]
Çalışmazsa yazabilirsin. :)

**Comment by efe3535** [comment]
Sanırım Python3.7 üzerinde linux_distribution da deprecate edilmiş. Yoğun utanç duygusuna bir yenisini ekleyerek koda bir modül daha ekledim, bu sefer kesssssin çalışır.
Modülü bulamazsa, `pip3 install distro` komutunu çalıştırmalısın.

**Comment by Afacanc38** [comment]
Deneyelim.

**Comment by Afacanc38** [comment]
Teşekkürler, çalıştı. Ama kullanıcı adı yerine bilgisayar adını gösteriyor. Nasıl kullanıcı adını göstermesini sağlayabilirim?
![Ekran Görüntüsü - 2021-05-27 10-22-27](https://user-images.githubusercontent.com/66299502/119783053-8397b080-bed5-11eb-8d43-f1c4308c1a77.png)

**Comment by efe3535** [comment]
Kusura bakmayın, kullanıcı adım ve bilgisayar adım aynıydı. O yüzden anlayamadım sanırım. :facepalm: 
Şimdi düzelmiş olmalı :)
